/**
 * engine/harness/common.cjs — helpers shared by every source and target adapter.
 *
 * Nothing here knows a client. Paths, guarded writes, directory links, managed
 * regions inside user-owned files, frontmatter, TOML string escaping, and the
 * secret detector that keeps token values out of generated config.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..', '..');
const GENERATED_MARK = 'GENERATED by agnostic-ai';

function expandPath(p, home = os.homedir()) {
  if (!p) return '';
  let resolved = String(p).replace(/%([^%]+)%/g, (_, n) => process.env[n] || '');
  if (resolved === '~') return home;
  if (resolved.startsWith('~/') || resolved.startsWith('~\\')) return path.join(home, resolved.slice(2));
  if (!path.isAbsolute(resolved)) return path.join(ROOT, resolved);
  return resolved;
}

/** Render an absolute path back to `~/...` for display and for generated headers. */
function tildePath(p, home = os.homedir()) {
  const norm = (s) => path.resolve(s).replace(/\\/g, '/').toLowerCase();
  const abs = path.resolve(p).replace(/\\/g, '/');
  return norm(p).startsWith(norm(home) + '/') ? '~' + abs.slice(path.resolve(home).length) : abs;
}

const readText = (p) => { try { return fs.readFileSync(p, 'utf8'); } catch (_) { return null; } };
const readJSON = (p) => { const raw = readText(p); if (raw == null) return null; try { return JSON.parse(raw); } catch (_) { return undefined; } };
const sha = (text) => crypto.createHash('sha256').update(String(text), 'utf8').digest('hex');

// ---------------------------------------------------------------------------
// Secret detection (patterns from core/safety/guards.json, fail closed)
// ---------------------------------------------------------------------------
const FALLBACK_SENSITIVE = [
  '(?i)sk-[0-9a-zA-Z]{20,}', '(?i)ghp_[0-9a-zA-Z]{36}', '(?i)xox[baprs]-[0-9a-zA-Z-]{10,}',
  '(?i)AIza[0-9A-Za-z-_]{35}', '(?i)-----BEGIN [A-Z ]*PRIVATE KEY-----', '(?i)bearer\\s+[a-zA-Z0-9_\\-\\.]{20,}',
];

function sensitivePatterns() {
  const guards = readJSON(path.join(ROOT, 'core', 'safety', 'guards.json'));
  const list = guards && guards.guards && guards.guards.secretScan && guards.guards.secretScan.sensitivePatterns;
  return (list && list.length ? list : FALLBACK_SENSITIVE).map((p) =>
    new RegExp(p.replace(/^\(\?i\)/, ''), p.startsWith('(?i)') ? 'i' : ''));
}

/**
 * True when a config VALUE looks like a credential: matches a known token
 * shape, or its key names a secret and the value is long and high-entropy.
 */
function looksSecret(key, value) {
  if (typeof value !== 'string' || !value) return false;
  if (/^\$\{[A-Za-z0-9_]+\}$/.test(value) || /^\$[A-Za-z0-9_]+$/.test(value)) return false; // already a reference
  if (sensitivePatterns().some((re) => re.test(value))) return true;
  const secretKey = /(key|token|secret|password|passwd|pwd|credential|auth)/i.test(String(key || ''));
  if (!secretKey) return false;
  if (value.length < 16) return false;
  if (/^(true|false|\d+|https?:\/\/[^\s]+)$/i.test(value)) return false;
  const classes = [/[a-z]/, /[A-Z]/, /\d/, /[^A-Za-z0-9]/].filter((re) => re.test(value)).length;
  return classes >= 2 && !/\s/.test(value);
}

// ---------------------------------------------------------------------------
// Guarded writes (same semantics as engine/sync/sync.cjs::writeGuarded)
// ---------------------------------------------------------------------------
function backupFile(backupsDir, tag, targetPath) {
  fs.mkdirSync(backupsDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const dest = path.join(backupsDir, `${tag}-${path.basename(targetPath)}-${stamp}.bak`);
  fs.copyFileSync(targetPath, dest);
  return dest;
}

/**
 * Build the `write(path, content, opts)` function handed to adapters.
 *   state.files[path] = sha of what we last wrote
 *   state.drift[path] = sha of a hand edit we already backed up (backup once)
 * A file whose first line still carries GENERATED_MARK (or the given `header`)
 * is ours to overwrite whatever touched it: the header IS the ownership claim.
 */
function makeWriter({ state, backupsDir, tag, check, force, log }) {
  state.files = state.files || {};
  state.drift = state.drift || {};
  return function write(targetPath, content, opts = {}) {
    const exists = fs.existsSync(targetPath);
    const existing = exists ? fs.readFileSync(targetPath, 'utf8') : null;
    if (existing === content) {
      state.files[targetPath] = sha(content);
      return { action: 'unchanged', backup: null };
    }
    const recorded = Object.prototype.hasOwnProperty.call(state.files, targetPath);
    // The ownership claim is the GENERATED mark inside the preamble (a title
    // line usually comes first). A title alone is not a claim: a user who keeps
    // the title and deletes the mark has taken the file over.
    const headLines = existing === null ? [] : existing.split(/\r?\n/, 6).slice(0, 5);
    const stillOurs = Boolean(existing !== null && headLines.some((l) => l.includes(GENERATED_MARK)));
    const managedRegion = Boolean(opts.region); // caller only replaces a marked region; the rest is the user's
    const drifted = Boolean(exists && recorded && state.files[targetPath] !== sha(existing) && !stillOurs && !managedRegion);
    if (check) return { action: drifted ? 'skipped-hand-edited' : 'would-write', backup: null };
    let backup = null;
    if (drifted) {
      if (state.drift[targetPath] !== sha(existing)) {
        backup = backupFile(backupsDir, tag, targetPath);
        state.drift[targetPath] = sha(existing);
      }
      if (!force) {
        if (log) log(`  ! skipped (hand-edited): ${targetPath}${backup ? ` (backup ${backup})` : ''}`);
        return { action: 'skipped-hand-edited', backup };
      }
    } else if (exists) {
      backup = backupFile(backupsDir, tag, targetPath);
    }
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.writeFileSync(targetPath, content, 'utf8');
    state.files[targetPath] = sha(content);
    delete state.drift[targetPath];
    return { action: 'written', backup };
  };
}

// ---------------------------------------------------------------------------
// Managed regions inside files the user also owns
// ---------------------------------------------------------------------------
const regionMarkers = (component, comment = '#') => ({
  start: `${comment} >>> agnostic-ai ${component} start (generated, do not edit)`,
  end: `${comment} <<< agnostic-ai ${component} end`,
});

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Replace (or append) the marked region; everything outside is preserved byte for byte. */
function replaceRegion(text, markers, body) {
  const re = new RegExp(`\\n*${escapeRe(markers.start)}[\\s\\S]*?${escapeRe(markers.end)}\\n?`, 'g');
  const region = body.trim() ? `${markers.start}\n${body.trimEnd()}\n${markers.end}\n` : '';
  const base = (text || '').replace(re, '\n');
  if (!region) return base.replace(/\n{3,}/g, '\n\n');
  return base.replace(/\n{3,}/g, '\n\n').replace(/\s*$/, base.trim() ? '\n\n' : '') + region;
}

function readRegion(text, markers) {
  const re = new RegExp(`${escapeRe(markers.start)}\\n([\\s\\S]*?)${escapeRe(markers.end)}`);
  const m = (text || '').match(re);
  return m ? m[1] : null;
}

// ---------------------------------------------------------------------------
// Directory links (junction on Windows, symlink elsewhere). Never replaces a real dir.
// ---------------------------------------------------------------------------
const plainPath = (p) => path.resolve(String(p).replace(/^\\\\\?\\/, '')).replace(/\\/g, '/').toLowerCase();

function readLinkTarget(p) {
  try { return fs.readlinkSync(p); } catch (_) { return null; }
}

function link(src, dest, { check } = {}) {
  const current = readLinkTarget(dest);
  if (current && plainPath(current) === plainPath(src)) return { action: 'unchanged' };
  // A real directory is never replaced, in check mode or otherwise; report the
  // same verdict both ways so --check after a clean apply stays clean.
  if (!current && fs.existsSync(dest)) return { action: 'skipped-real-directory' };
  if (check) return { action: 'would-link' };
  if (current) fs.rmSync(dest, { recursive: true, force: true });
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  try {
    fs.symlinkSync(src, dest, 'junction');
  } catch (err) {
    if (process.platform !== 'win32') throw err;
    execSync(`cmd /c mklink /J "${dest}" "${src}"`, { stdio: 'pipe' });
  }
  return { action: 'linked' };
}

function unlinkIfLink(dest) {
  if (readLinkTarget(dest) === null) return false;
  fs.rmSync(dest, { recursive: true, force: true });
  return true;
}

// ---------------------------------------------------------------------------
// Markdown frontmatter + TOML strings
// ---------------------------------------------------------------------------
function parseFrontmatter(md) {
  const m = String(md).match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { meta: {}, body: String(md) };
  const meta = {};
  let key = null;
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$/);
    if (kv) { key = kv[1]; meta[key] = kv[2].trim().replace(/^["'](.*)["']$/, '$1'); }
    else if (key && /^\s+\S/.test(line)) meta[key] = `${meta[key]} ${line.trim()}`.trim(); // folded continuation
  }
  return { meta, body: m[2] };
}

/**
 * Quote a frontmatter value when YAML would otherwise read it as something
 * else: `[a b]` is a flow sequence, `{}` a map, `yes`/`no`/`true`/`1.5` typed
 * scalars, a leading `*`, `&`, `!`, `%`, `@`, `` ` ``, `|`, `>`, `'`, `"`, `#`
 * or a `: ` / ` #` inside changes the parse. Bit 2026-09-06: an argument-hint
 * of `[text to translate]` was emitted bare and became a one-item list.
 */
function yamlScalar(v) {
  const s = String(v);
  // Typed scalars (true, 12, null) are left bare on purpose: `readonly: true`
  // and `alwaysApply: true` must stay booleans for the client that reads them.
  const risky = /^[[\]{}*&!%@`|>'"#,?-]|: | #|^\s|\s$/;
  return risky.test(s) ? JSON.stringify(s) : s;
}

function renderFrontmatter(meta, body) {
  const lines = ['---'];
  for (const [k, v] of Object.entries(meta)) if (v !== undefined && v !== null && v !== '') lines.push(`${k}: ${yamlScalar(v)}`);
  lines.push('---');
  return `${lines.join('\n')}\n\n${String(body).trim()}\n`;
}

const tomlStr = (s) => JSON.stringify(String(s)); // TOML basic strings share JSON escaping
function tomlMultiline(s) {
  return '"""\n' + String(s).replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"') + '\n"""';
}

/** List the skill directories (entries holding a SKILL.md) under a dir. Follows links. */
function listSkills(dir) {
  const out = [];
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch (_) { return out; }
  for (const e of entries) {
    if (e.name.startsWith('.')) continue;
    const full = path.join(dir, e.name);
    let isDir = e.isDirectory();
    if (e.isSymbolicLink()) { try { isDir = fs.statSync(full).isDirectory(); } catch (_) { isDir = false; } }
    if (isDir && fs.existsSync(path.join(full, 'SKILL.md'))) out.push({ name: e.name, path: full, link: readLinkTarget(full) });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

module.exports = {
  ROOT, GENERATED_MARK, expandPath, tildePath, readText, readJSON, sha,
  looksSecret, sensitivePatterns,
  makeWriter, backupFile,
  regionMarkers, replaceRegion, readRegion, escapeRe,
  link, unlinkIfLink, readLinkTarget, plainPath, listSkills,
  parseFrontmatter, renderFrontmatter, yamlScalar, tomlStr, tomlMultiline,
};
